TZ=Asia/Manila

app_server_ip=192.168.1.2
local_etracs_host=192.168.1.2:8070
gdx_host=192.168.1.2

channel=169

dbserver_host=110.100.210.7
dbserver_user=sa
dbserver_pass=1paSsword1

db_main=etracs25_iligan
db_image=etracs25_iligan_image
db_notification=etracs25_iligan_notification
